version: '3.8'
services:
  db:
    container_name: document_db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: document_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  doc_app:
    container_name: document_app
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: document_db
      DB_PORT: 5432
      DB_SSL_MODE: disable
      PORT: 8080
    ports:
      - "8080:8080"
