basePath: /
definitions:
  models.Document:
    properties:
      author:
        type: string
      content:
        type: string
      createdAt:
        type: string
      id:
        type: integer
      title:
        type: string
      updatedAt:
        type: string
    type: object
  models.SwaggerErrorResponse:
    properties:
      error:
        example: error message
        type: string
    type: object
  models.SwaggerSuccessResponse:
    properties:
      message:
        example: success message
        type: string
    type: object
host: localhost:8888
info:
  contact: {}
  description: This is a API for managing documents.
  title: Documents Service API
  version: "1.0"
paths:
  /documents/:
    get:
      description: Get all documents
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Document'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.SwaggerErrorResponse'
      summary: Get all documents
      tags:
      - documents
    post:
      consumes:
      - application/json
      description: Create a new document with the input payload
      parameters:
      - description: Create document
        in: body
        name: document
        required: true
        schema:
          $ref: '#/definitions/models.Document'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Document'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.SwaggerErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.SwaggerErrorResponse'
      summary: Create a new document
      tags:
      - documents
  /documents/{id}:
    delete:
      description: Delete a document by ID
      parameters:
      - description: Document ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SwaggerSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.SwaggerErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.SwaggerErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.SwaggerErrorResponse'
      summary: Delete a document
      tags:
      - documents
    get:
      description: Get document by ID
      parameters:
      - description: Document ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Document'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.SwaggerErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.SwaggerErrorResponse'
      summary: Get document by ID
      tags:
      - documents
    put:
      consumes:
      - application/json
      description: Update a document with the input payload
      parameters:
      - description: Document ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update document
        in: body
        name: document
        required: true
        schema:
          $ref: '#/definitions/models.Document'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SwaggerSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.SwaggerErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.SwaggerErrorResponse'
      summary: Update a document
      tags:
      - documents
swagger: "2.0"
